### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by Immortalin** [andygeiss/esp32-transpiler#1]
How does this handle garbage collection? Arduino code is basically C++

**Comment by andygeiss** [comment]
Go handles garbage collection in the background. So its not possible to translate triggered Go garbage collection to C++ garbage collection.
esp32-transpiler is based on calling the Arduino API (https://www.arduino.cc/reference/en/), which is able to do things like allocation under the hood.

**Comment by Immortalin** [comment]
I see, would you mind adding this to the README? How garbage collection works is pretty important for hard real-time systems.
